# Generated by Django 4.2.26 on 2025-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('request_date', models.DateField()),
            ],
        ),
    ]
